# Generated by Django 6.0.6 on 2026-06-11 14:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSearchConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("remote_only", models.BooleanField(default=False)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("employment_types", models.JSONField(blank=True, default=list)),
                (
                    "fetch_schedule_cron",
                    models.CharField(default="0 6 * * *", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_search_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="ix_job_cfg_user_active"
                    ),
                    models.Index(
                        fields=["fetch_schedule_cron"], name="ix_job_cfg_schedule"
                    ),
                ],
            },
        ),
    ]
