# Generated by Django 6.0.6 on 2026-06-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="payload",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
