# Generated by Django 6.0.6 on 2026-06-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_date_joined_alter_user_first_name_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmation_token_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="ix_django_users_username"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["full_name"], name="ix_django_users_full_name"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_confirmation_token_hash"],
                name="ix_django_users_confirm_token",
            ),
        ),
    ]
