# Generated by Django 6.0.6 on 2026-06-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email_confirmation_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="ix_django_users_full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
    ]
