# Generated by Django 6.0.6 on 2026-07-27 08:09

import pgvector.django.vector
import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userprofile_ix_django_users_full_name"),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name="userprofile",
            name="profile_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=2048, null=True
            ),
        ),
    ]
