# Generated by Django 6.0.6 on 2026-06-11 14:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("professional_summary", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("domain", models.CharField(blank=True, max_length=100)),
                ("values_statement", models.TextField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("cv_storage_path", models.CharField(blank=True, max_length=512)),
                ("master_cv_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="ix_profiles_user"),
                    models.Index(fields=["domain"], name="ix_profiles_domain"),
                ],
            },
        ),
    ]
