# Generated by Django 6.0.6 on 2026-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_ix_django_users_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
