# Generated by Django 6.0.6 on 2026-06-30 16:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSourceProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("docs_url", models.URLField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("robots_notes", models.TextField(blank=True)),
                ("terms_notes", models.TextField(blank=True)),
                ("last_discovered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status"], name="ix_job_src_provider_status")
                ],
            },
        ),
        migrations.CreateModel(
            name="JobSourceConfigDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("validation_failed", "Validation failed"),
                            ("validated", "Validated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="generated",
                        max_length=32,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0)),
                ("evidence_urls", models.JSONField(blank=True, default=list)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_drafts",
                        to="jobs.jobsourceprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSourceValidationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                ("request_url", models.URLField(max_length=2048)),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_runs",
                        to="jobs.jobsourceconfigdraft",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_job_id", models.CharField(max_length=512)),
                ("source_api", models.CharField(max_length=128)),
                ("raw_payload", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_jobs",
                        to="jobs.jobsearchconfig",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_jobs",
                        to="jobs.jobsourceprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_job_id", models.CharField(max_length=512, unique=True)),
                ("title", models.CharField(max_length=512)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("company_website", models.URLField(blank=True, max_length=2048)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("remote_flag", models.BooleanField(default=False)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("employment_type", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("application_url", models.URLField(blank=True, max_length=2048)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("parsed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "raw_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="job_posting",
                        to="jobs.rawjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="jobsourceconfigdraft",
            index=models.Index(
                fields=["provider", "status"], name="ix_job_src_draft_status"
            ),
        ),
        migrations.AddIndex(
            model_name="jobsourcevalidationrun",
            index=models.Index(
                fields=["draft", "created_at"], name="ix_job_src_val_draft"
            ),
        ),
        migrations.AddIndex(
            model_name="rawjob",
            index=models.Index(
                fields=["user", "parse_status"], name="ix_raw_jobs_user_parse"
            ),
        ),
        migrations.AddIndex(
            model_name="rawjob",
            index=models.Index(
                fields=["config", "fetched_at"], name="ix_raw_jobs_cfg_fetched"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawjob",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_job_id"),
                name="uq_raw_job_provider_external_id",
            ),
        ),
    ]
