# Generated by Django 6.0.6 on 2026-07-21 04:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def supersede_duplicate_approved_drafts(apps, schema_editor):
    draft_model = apps.get_model("jobs", "JobSourceConfigDraft")
    provider_ids = (
        draft_model.objects.filter(status="approved")
        .values_list("provider_id", flat=True)
        .distinct()
    )
    for provider_id in provider_ids:
        approved_ids = list(
            draft_model.objects.filter(provider_id=provider_id, status="approved")
            .order_by("-approved_at", "-created_at")
            .values_list("id", flat=True)
        )
        if len(approved_ids) > 1:
            draft_model.objects.filter(id__in=approved_ids[1:]).update(status="superseded")


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_jobsourceprovider_jobsourceconfigdraft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSourceDiscoveryRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("known_auth_type", models.CharField(blank=True, max_length=32)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="jobsourceconfigdraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("validation_failed", "Validation failed"),
                    ("validated", "Validated"),
                    ("approved", "Approved"),
                    ("superseded", "Superseded"),
                    ("rejected", "Rejected"),
                ],
                default="generated",
                max_length=32,
            ),
        ),
        migrations.RunPython(supersede_duplicate_approved_drafts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="jobsourceconfigdraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("provider",),
                name="uq_job_src_one_approved_draft",
            ),
        ),
        migrations.AddField(
            model_name="jobsourcediscoveryrun",
            name="draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discovery_runs",
                to="jobs.jobsourceconfigdraft",
            ),
        ),
        migrations.AddField(
            model_name="jobsourcediscoveryrun",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discovery_runs",
                to="jobs.jobsourceprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="jobsourcediscoveryrun",
            index=models.Index(fields=["provider", "-queued_at"], name="ix_job_src_disc_provider"),
        ),
        migrations.AddIndex(
            model_name="jobsourcediscoveryrun",
            index=models.Index(fields=["status"], name="ix_job_src_disc_status"),
        ),
    ]
