# Generated by Django 6.0.6 on 2026-07-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobsourcediscoveryrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsourcevalidationrun",
            name="request_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobsourcevalidationrun",
            name="response_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
