# Generated by Django 6.0.6 on 2026-07-27 08:09

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobsourcevalidationrun_request_headers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name="CompanySummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("selected_website", models.URLField(blank=True, max_length=2048)),
                ("selection_confidence", models.FloatField(default=0)),
                ("source_urls", models.JSONField(blank=True, default=list)),
                ("source_evidence", models.JSONField(blank=True, default=list)),
                ("raw_scraped_content", models.TextField(blank=True)),
                ("mission", models.TextField(blank=True)),
                ("values", models.TextField(blank=True)),
                ("culture", models.TextField(blank=True)),
                ("tech_stack", models.TextField(blank=True)),
                ("team_size_approx", models.CharField(blank=True, max_length=255)),
                ("recent_news", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("field_citations", models.JSONField(blank=True, default=dict)),
                ("synthesis_model", models.CharField(blank=True, max_length=255)),
                ("failure_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "retrieved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="JobEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pass1_scores", models.JSONField(default=dict)),
                ("pass1_notes", models.TextField(blank=True)),
                ("pass2_critique", models.TextField(blank=True)),
                ("pass2_revised_scores", models.JSONField(default=dict)),
                (
                    "final_classification",
                    models.CharField(
                        choices=[
                            ("good_fit", "Good fit"),
                            ("maybe", "Maybe"),
                            ("reject", "Reject"),
                        ],
                        max_length=32,
                    ),
                ),
                ("final_feedback", models.TextField(blank=True)),
                ("overall_score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("dimension_scores", models.JSONField(default=dict)),
                ("rejection_source", models.CharField(blank=True, max_length=64)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="jobposting",
            name="description_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=2048, null=True
            ),
        ),
        migrations.AddField(
            model_name="rawjob",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["raw_job", "parsed_at"], name="ix_job_post_raw_parsed"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["company_name"], name="ix_job_post_company"),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["posted_date"], name="ix_job_post_date"),
        ),
        migrations.AddField(
            model_name="companysummary",
            name="job_posting",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_summary",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="jobevaluation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="companysummary",
            index=models.Index(
                fields=["job_posting", "expires_at"], name="ix_company_sum_expiry"
            ),
        ),
        migrations.AddIndex(
            model_name="companysummary",
            index=models.Index(fields=["company_name"], name="ix_company_sum_name"),
        ),
        migrations.AddIndex(
            model_name="jobevaluation",
            index=models.Index(
                fields=["user", "final_classification"], name="ix_job_eval_user_class"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevaluation",
            index=models.Index(
                fields=["user", "-evaluated_at"], name="ix_job_eval_user_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobevaluation",
            constraint=models.UniqueConstraint(
                fields=("job_posting", "user"), name="uq_job_eval_posting_user"
            ),
        ),
    ]
