# Generated by Django 6.0.6 on 2026-07-27 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_companysummary_jobevaluation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rawjob",
            name="uq_raw_job_provider_external_id",
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_jobs",
                to="jobs.jobsearchconfig",
            ),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_jobs",
                to="jobs.jobsourceprovider",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawjob",
            constraint=models.UniqueConstraint(
                fields=("user", "source_api", "external_job_id"),
                name="uq_raw_job_user_source_external",
            ),
        ),
    ]
