# Generated by Django 6.0.6 on 2026-07-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_remove_rawjob_uq_raw_job_provider_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="external_job_id",
            field=models.CharField(max_length=512),
        ),
    ]
