# Generated by Django 6.0.6 on 2026-07-27 08:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0005_companysummary_jobevaluation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDoc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tailored_cv_text", models.TextField()),
                ("cover_letter_text", models.TextField()),
                ("cv_pdf_path", models.CharField(blank=True, max_length=512)),
                ("cover_letter_pdf_path", models.CharField(blank=True, max_length=512)),
                ("generation_model", models.CharField(max_length=255)),
                ("quality_passed", models.BooleanField(default=False)),
                ("quality_notes", models.TextField(blank=True)),
                (
                    "last_edited_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job_evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_doc",
                        to="jobs.jobevaluation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"], name="ix_app_doc_user_time"
                    )
                ],
            },
        ),
    ]
